/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Webber_Jiang
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
        allClear();
        updateDisplay();
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        display = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        plusminus = new javax.swing.JButton();
        sqaureroot = new javax.swing.JButton();
        C = new javax.swing.JButton();
        AC = new javax.swing.JButton();
        num1 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        num7 = new javax.swing.JButton();
        num8 = new javax.swing.JButton();
        num9 = new javax.swing.JButton();
        muti = new javax.swing.JButton();
        decimal = new javax.swing.JButton();
        num0 = new javax.swing.JButton();
        euqal = new javax.swing.JButton();
        divsion = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        quit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        about = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        display.setEditable(false);
        display.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        display.setMargin(new java.awt.Insets(15, 15, 15, 15));
        display.setName("Display"); // NOI18N
        getContentPane().add(display, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(5, 4));

        plusminus.setMnemonic(' ');
        plusminus.setText("±");
        plusminus.setToolTipText("");
        plusminus.setName(" ±"); // NOI18N
        plusminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorButtonPressed(evt);
            }
        });
        jPanel1.add(plusminus);

        sqaureroot.setText("√");
        sqaureroot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorButtonPressed(evt);
            }
        });
        jPanel1.add(sqaureroot);

        C.setText("C");
        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorButtonPressed(evt);
            }
        });
        jPanel1.add(C);

        AC.setText("AC");
        AC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorButtonPressed(evt);
            }
        });
        jPanel1.add(AC);

        num1.setText("1");
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorButtonPressed(evt);
            }
        });
        jPanel1.add(num1);

        num2.setText("2");
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorButtonPressed(evt);
            }
        });
        jPanel1.add(num2);

        num3.setText("3");
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorButtonPressed(evt);
            }
        });
        jPanel1.add(num3);

        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorButtonPressed(evt);
            }
        });
        jPanel1.add(plus);

        num4.setText("4");
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorButtonPressed(evt);
            }
        });
        jPanel1.add(num4);

        num5.setText("5");
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorButtonPressed(evt);
            }
        });
        jPanel1.add(num5);

        num6.setText("6");
        num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorButtonPressed(evt);
            }
        });
        jPanel1.add(num6);

        minus.setText("-");
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorButtonPressed(evt);
            }
        });
        jPanel1.add(minus);

        num7.setText("7");
        num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorButtonPressed(evt);
            }
        });
        jPanel1.add(num7);

        num8.setText("8");
        num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorButtonPressed(evt);
            }
        });
        jPanel1.add(num8);

        num9.setText("9");
        num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorButtonPressed(evt);
            }
        });
        jPanel1.add(num9);

        muti.setText("x");
        muti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorButtonPressed(evt);
            }
        });
        jPanel1.add(muti);

        decimal.setText(".");
        decimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorButtonPressed(evt);
            }
        });
        jPanel1.add(decimal);

        num0.setText("0");
        num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorButtonPressed(evt);
            }
        });
        jPanel1.add(num0);

        euqal.setText("=");
        euqal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorButtonPressed(evt);
            }
        });
        jPanel1.add(euqal);

        divsion.setText("÷");
        divsion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorButtonPressed(evt);
            }
        });
        jPanel1.add(divsion);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        quit.setText("Quit");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });
        jMenu1.add(quit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        about.setText("About");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        jMenu2.add(about);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
       System.exit(0); // TODO add your handling code here:
    }//GEN-LAST:event_quitActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        javax.swing.JOptionPane.showMessageDialog(null, "Webber Jiang" +"\n2019"+"\nDebug is life!");// TODO add your handling code here:
    }//GEN-LAST:event_aboutActionPerformed

    private void calculatorButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatorButtonPressed
      onButtonPressed((javax.swing.JButton)evt.getSource());// TODO add your handling code here:
    }//GEN-LAST:event_calculatorButtonPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AC;
    private javax.swing.JButton C;
    private javax.swing.JMenuItem about;
    private javax.swing.JButton decimal;
    private javax.swing.JTextField display;
    private javax.swing.JButton divsion;
    private javax.swing.JButton euqal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton minus;
    private javax.swing.JButton muti;
    private javax.swing.JButton num0;
    private javax.swing.JButton num1;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton num9;
    private javax.swing.JButton plus;
    private javax.swing.JButton plusminus;
    private javax.swing.JMenuItem quit;
    private javax.swing.JButton sqaureroot;
    // End of variables declaration//GEN-END:variables

private double result ;
private char operation ;
private boolean error ;
private int displayLen ;
private String disp ;
public static final int MAX_DISPLAY_LEN = 10;
public static final double MAX_VALUE_EXCLUSIVE = 10000000000.0;
private void allClear ()
{
result = 0.0;
operation = '+';
error = false ;
displayLen = 0;
disp = " " ;
}
// Avoids " scientific notation " format for large numbers ;
// and guaranteed to give us too many digits . We then just
// truncate away the ones we don 't need .
private String toDisplayString (double d )
{
String asStr = String.format ("%."+(MAX_DISPLAY_LEN)+"f",
d ) ;
int maxLen = MAX_DISPLAY_LEN ;
if( asStr . charAt (0) == '-') {
maxLen += 1;
}
asStr = asStr . substring (0 , maxLen ) ;
return asStr ;
}
private void updateDisplay ()
{
if ( error )
{
    display.setText ( " Err " ) ;
}
else if( displayLen > 0)
{
    display.setText ( disp ) ;
}
else
{
    display.setText ( toDisplayString ( result ) ) ;
}
}   
  private void exec ( double immediateValue )
{
System . out . println ( result ) ;
System . out . println ( operation ) ;
System . out . println ( immediateValue ) ;
switch ( operation )
{
case '=':
result = immediateValue ;
break ;
case '+':
result += immediateValue ;
break ;
case '-':
result -= immediateValue ;
break ;
case 'x':
result *= immediateValue ;
break ;
case '÷':
if ( immediateValue == 0)
{
error = true ;
}
else
{
result /= immediateValue ;
}
break ;
}
System . out . println ( " := > " + result ) ;
double check = Math . abs ( result ) ;
if ( check >= MAX_VALUE_EXCLUSIVE )
{
error = true ;
}
displayLen = 0;
disp = " " ;
}  
  private void handlePress (char code )
{
if ( code == 'A')
{
allClear () ;
return ;
}
if( error )
{
return ;
}
if( code == 'C')
{
disp = " " ;
displayLen = 0;
}
else if( code >= '0' && code <= '9' || code == '.' ) {
if( code == '.' && disp . indexOf ('.') != -1)
{
// Just ignore the button press ; can 't have more than one '.'
// This is sometimes called " eating " user input .
}
else if ( displayLen < MAX_DISPLAY_LEN + ( code == '.' ? 1 : 0) )
{
// special case - if disp is "0" , just overwrite it.
if ( " 0 " . equals ( disp ) && code != '.')
{
disp = " " + code ;
}
else
{
disp += code ;
displayLen += 1;
}
}
}
else if ( code == 'r' || code == '±')
{
double value = displayLen == 0 ? result : Double . valueOf ( disp ) ;
final double intermediate ;
if( code == 'r')
{
if( value < 0)
{
error = true ;
return ;
}
intermediate = Math . sqrt ( value ) ;
}
else
{
intermediate = - value ;
}
disp = toDisplayString ( intermediate ) ;
displayLen = disp . length () ;
}
else
{
double value = displayLen == 0 ? result : Double . valueOf ( disp ) ;
exec ( value ) ;
}
}
private void onButtonPressed (javax.swing . JButton which )
{
// Step 1 - Turn `which ` into a letter
String buttonText = which . getText () ;
final char letter ;
if( "<html>&radic;</html>".equals(buttonText) || "√" . equals (buttonText))
{
letter = 'r';
}
else
{
letter = buttonText . charAt (0) ;
}
// Step 2 - Apply the effect of that button ( see the " Background "
// section in the handout ).
handlePress ( letter ) ;
// Step 3 - change what 's shown in the `display ` JTextField .
updateDisplay () ;
}
}